# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=160, verbose_name='Задача')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Редакция')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последняя Редакция')),
                ('image', models.ImageField(upload_to='images/')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'список задач',
                'verbose_name_plural': 'списки задач',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tasklist.TaskList'),
        ),
        migrations.AlterUniqueTogether(
            name='tasklist',
            unique_together=set([('title', 'created')]),
        ),
    ]
