# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0003_auto_20170623_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklistimage',
            options={'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasklist.TaskList'),
        ),
    ]
