# Generated by Django 2.2.5 on 2019-09-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0006_auto_20170630_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklistimage',
            name='tasklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasklist.TaskList'),
        ),
    ]
